/** Thông tin công ty */
export const company = {
  "title": "Thông tin Doanh nghiệp",
  "description": "Thiết lập thông tin định danh và thương hiệu hiển thị trên hệ thống.",
  "brandSection": "Thương hiệu & Logo",
  "dropImage": "Thả ảnh vào đây",
  "upload": "Tải lên",
  "dragDrop": "Kéo thả",
  "capture": "Chụp",
  "imageHint": "Hỗ trợ PNG, JPG, WebP. Tối đa 2MB.",
  "appName": "Tên Ứng dụng",
  "appNamePlaceholder": "Ví dụ: 5F template",
  "appNameHint": "Hiển thị trên Sidebar và tiêu đề Browser.",
  "appDescription": "Mô tả ngắn",
  "appDescPlaceholder": "Ví dụ: Ứng dụng mẫu quản lý ERP",
  "appDescHint": "Hiển thị dưới tên ứng dụng ở Sidebar.",
  "legalSection": "Thông tin pháp nhân",
  "companyName": "Tên Công ty đầy đủ",
  "companyNamePlaceholder": "Công ty Cổ phần...",
  "taxId": "Mã số thuế",
  "taxIdPlaceholder": "010xxxxxxx",
  "phone": "Số điện thoại",
  "phonePlaceholder": "(+84) ...",
  "email": "Email liên hệ",
  "emailPlaceholder": "contact@company.com",
  "website": "Website",
  "websitePlaceholder": "www.company.com",
  "address": "Địa chỉ trụ sở",
  "addressPlaceholder": "Số nhà, đường, phường/xã...",
  "saveButton": "Lưu thông tin",
  "imageTypeError": "Vui lòng chỉ tải lên file hình ảnh.",
  "imageSizeError": "Kích thước ảnh không được vượt quá 2MB",
  "saveSuccess": "Cập nhật thông tin công ty thành công!",
  "validation": {
    "appNameMin": "Tên ứng dụng quá ngắn",
    "appDescMax": "Mô tả ngắn không được quá 30 ký tự",
    "companyNameMin": "Tên công ty là bắt buộc",
    "taxIdMin": "Mã số thuế không hợp lệ",
    "emailInvalid": "Email không hợp lệ"
  }
} as const;
