/** Phòng ban */
export const department = {
  "exportCode": "Mã phòng ban",
  "exportName": "Tên phòng ban",
  "exportLevel": "Cấp độ",
  "exportOrder": "Thứ tự",
  "exportStatus": "Trạng thái",
  "exportSuccess": "Xuất file thành công",
  "noExportData": "Không có dữ liệu để xuất",
  "importDeveloping": "Chức năng Import đang phát triển",
  "toolbar": {
    "department": "Phòng"
  },
  "footerRecords": "bản ghi",
  "title": "Phòng ban",
  "pageTitle": "Cơ cấu tổ chức",
  "pageDescription": "Quản lý sơ đồ phòng ban và phân cấp đơn vị.",
  "addButton": "Thêm phòng ban",
  "searchPlaceholder": "Tìm kiếm theo tên hoặc mã phòng...",
  "totalCount": "Tổng số: {{count}} đơn vị",
  "deleteTitle": "Xóa phòng ban",
  "deleteMessage": "Bạn có chắc chắn muốn xóa phòng ban này? Lưu ý: Không thể xóa nếu phòng ban đang có cấp con.",
  "loading": "Đang tải cấu trúc phòng ban...",
  "empty": "Chưa có phòng ban nào",
  "emptyHint": "Hãy tạo phòng ban đầu tiên để thiết lập cơ cấu tổ chức.",
  "name": "Tên phòng ban",
  "code": "Mã số",
  "level": "Cấp độ",
  "levelBadge": "Level {{level}}",
  "active": "Hoạt động",
  "inactive": "Ngừng",
  "form": {
    "editTitle": "Chỉnh sửa phòng ban",
    "createTitle": "Thêm phòng ban mới",
    "code": "Mã phòng ban",
    "codePlaceholder": "VD: IT_DEV (Chữ hoa, không dấu)",
    "name": "Tên phòng ban",
    "namePlaceholder": "VD: Phòng Phát triển Phần mềm",
    "parent": "Phòng ban cấp trên",
    "parentNone": "-- Không (Là cấp cao nhất) --",
    "parentHint": "Chọn phòng ban quản lý trực tiếp.",
    "sortOrder": "Thứ tự hiển thị",
    "status": "Trạng thái",
    "statusActive": "Đang hoạt động",
    "statusInactive": "Ngừng hoạt động",
    "description": "Mô tả",
    "descriptionPlaceholder": "Nhập mô tả ngắn về phòng ban..."
  },
  "validation": {
    "codeMin": "Mã phòng ban phải có ít nhất 2 ký tự",
    "codeMax": "Mã phòng ban tối đa 50 ký tự",
    "codeFormat": "Mã chỉ chứa chữ hoa, số và gạch dưới (VD: IT_DEV)",
    "nameMin": "Tên phòng ban phải có ít nhất 3 ký tự",
    "nameMax": "Tên phòng ban quá dài",
    "statusInvalid": "Trạng thái không hợp lệ",
    "sortOrderMin": "Thứ tự phải lớn hơn hoặc bằng 0"
  },
  "toast": {
    "createSuccess": "Tạo phòng ban thành công",
    "updateSuccess": "Cập nhật thành công",
    "deleteSuccess": "Xóa phòng ban thành công",
    "importSuccess": "Đã import {{count}} phòng ban"
  },
  "importTemplateName": "Mau_Import_Phong_Ban",
  "service": {
    "notFound": "Phòng ban không tồn tại",
    "hasChildren": "Không thể xóa phòng ban đang chứa phòng ban con."
  },
  "detail": {
    "title": "Chi tiết phòng ban",
    "activate": "Kích hoạt",
    "deactivate": "Ngưng",
    "level": "Cấp độ",
    "order": "Thứ tự",
    "parent": "Phòng ban cấp trên",
    "noParent": "— Không (cấp cao nhất) —",
    "updated": "Cập nhật",
    "createdAt": "Được tạo lúc",
    "basicInfo": "Thông tin cơ bản",
    "systemInfo": "Thông tin hệ thống",
    "description": "Mô tả",
    "childrenSection": "Phòng ban con",
    "addChild": "Thêm",
    "noChildren": "Chưa có phòng ban con",
    "noChildrenHint": "Bấm Thêm phòng ban con để tạo đơn vị cấp dưới trực tiếp."
  },
  "store": {
    "orderCol": "Thứ tự",
    "nameCol": "Tên phòng ban",
    "codeCol": "Mã số",
    "descCol": "Mô tả",
    "levelCol": "Cấp độ",
    "statusCol": "Trạng thái",
    "parentCol": "Phòng cấp trên",
    "updatedCol": "Cập nhật"
  },
  "statusChangeTitle": "Chuyển trạng thái phòng ban",
  "statusChangeMessage": "Chuyển \"{{name}}\" sang trạng thái {{status}}?"
} as const;
