import type { Employee } from '../core/types';
import type { EmployeeFormValues } from '../core/schema';

/**
 * Giá trị mặc định cho form tạo mới nhân viên.
 * Dùng làm defaultValues và khi reset form (create mode).
 */
export function getDefaultEmployeeFormValues(ngayVaoLam: string): EmployeeFormValues {
  return {
    ma_nhan_vien: '',
    ho_ten: '',
    email: '',
    so_dien_thoai: '',
    chuc_vu_id: '',
    phong_ban_id: '',
    chi_nhanh_id: '',
    gioi_tinh: 'Nam',
    trang_thai: 'Đang làm việc',
    ngay_vao_lam: ngayVaoLam,
    anh_dai_dien: '',
    ngay_sinh: '',
    cmnd_cccd: '',
    ngay_cap_cccd: '',
    noi_cap_cccd: '',
    quoc_tich: '',
    dan_toc: '',
    ton_giao: '',
    tinh_thanh: '',
    quan_huyen: '',
    phuong_xa: '',
    dia_chi_cu_the: '',
    dia_chi_tam_tru: '',
    cap_bac_id: '',
    loai_hop_dong: '',
    ngay_het_han_hd: '',
    noi_lam_viec: '',
    email_ca_nhan: '',
    nguoi_lien_he_khan_cap: '',
    sdt_khan_cap: '',
    quan_he_khan_cap: '',
    tinh_trang_hon_nhan: '',
    so_nguoi_phu_thuoc: undefined,
    trinh_do_hoc_van: '',
    chuyen_nganh: '',
    truong_hoc: '',
    nam_tot_nghiep: '',
    chung_chi: '',
    so_tai_khoan: '',
    ten_ngan_hang: '',
    chi_nhanh_nh: '',
    ma_so_thue_ca_nhan: '',
    so_bhxh: '',
    so_bhyt: '',
    ngay_tham_gia_bh: '',
    noi_dang_ky_kcb: '',
  };
}

/**
 * Map Employee to EmployeeFormValues for use in update (e.g. Profile page).
 * Required fields use fallback empty string when null so type is satisfied.
 */
export function employeeToFormValues(emp: Employee): EmployeeFormValues {
  return {
    ma_nhan_vien: emp.ma_nhan_vien,
    ho_ten: emp.ho_ten,
    email: emp.email,
    so_dien_thoai: emp.so_dien_thoai,
    chuc_vu_id: emp.chuc_vu_id ?? '',
    phong_ban_id: emp.phong_ban_id ?? '',
    chi_nhanh_id: emp.chi_nhanh_id ?? undefined,
    gioi_tinh: emp.gioi_tinh,
    trang_thai: emp.trang_thai,
    ngay_vao_lam: emp.ngay_vao_lam,
    anh_dai_dien: emp.anh_dai_dien ?? undefined,
    ngay_sinh: emp.ngay_sinh ?? undefined,
    cmnd_cccd: emp.cmnd_cccd ?? undefined,
    ngay_cap_cccd: emp.ngay_cap_cccd ?? undefined,
    noi_cap_cccd: emp.noi_cap_cccd ?? undefined,
    quoc_tich: emp.quoc_tich ?? undefined,
    dan_toc: emp.dan_toc ?? undefined,
    ton_giao: emp.ton_giao ?? undefined,
    tinh_thanh: emp.tinh_thanh ?? undefined,
    quan_huyen: emp.quan_huyen ?? undefined,
    phuong_xa: emp.phuong_xa ?? undefined,
    dia_chi_cu_the: emp.dia_chi_cu_the ?? undefined,
    dia_chi_tam_tru: emp.dia_chi_tam_tru ?? undefined,
    cap_bac_id: emp.cap_bac_id ?? undefined,
    loai_hop_dong: emp.loai_hop_dong ?? undefined,
    ngay_het_han_hd: emp.ngay_het_han_hd ?? undefined,
    noi_lam_viec: emp.noi_lam_viec ?? undefined,
    email_ca_nhan: emp.email_ca_nhan ?? undefined,
    nguoi_lien_he_khan_cap: emp.nguoi_lien_he_khan_cap ?? undefined,
    sdt_khan_cap: emp.sdt_khan_cap ?? undefined,
    quan_he_khan_cap: emp.quan_he_khan_cap ?? undefined,
    tinh_trang_hon_nhan: emp.tinh_trang_hon_nhan ?? undefined,
    so_nguoi_phu_thuoc: emp.so_nguoi_phu_thuoc ?? undefined,
    trinh_do_hoc_van: emp.trinh_do_hoc_van ?? undefined,
    chuyen_nganh: emp.chuyen_nganh ?? undefined,
    truong_hoc: emp.truong_hoc ?? undefined,
    nam_tot_nghiep: emp.nam_tot_nghiep ?? undefined,
    chung_chi: emp.chung_chi ?? undefined,
    so_tai_khoan: emp.so_tai_khoan ?? undefined,
    ten_ngan_hang: emp.ten_ngan_hang ?? undefined,
    chi_nhanh_nh: emp.chi_nhanh_nh ?? undefined,
    ma_so_thue_ca_nhan: emp.ma_so_thue_ca_nhan ?? undefined,
    so_bhxh: emp.so_bhxh ?? undefined,
    so_bhyt: emp.so_bhyt ?? undefined,
    ngay_tham_gia_bh: emp.ngay_tham_gia_bh ?? undefined,
    noi_dang_ky_kcb: emp.noi_dang_ky_kcb ?? undefined,
  };
}
