/** Chữ giao diện dùng chung (nav, trang, lỗi, …) */
export const ui = {
  "nav": {
    "changePassword": {
      "title": "Đổi mật khẩu",
      "description": "Nhập mật khẩu hiện tại và mật khẩu mới để bảo mật tài khoản.",
      "currentPassword": "Mật khẩu hiện tại",
      "newPassword": "Mật khẩu mới",
      "confirmPassword": "Xác nhận mật khẩu mới",
      "showPassword": "Hiện mật khẩu",
      "hidePassword": "Ẩn mật khẩu",
      "newPasswordHint": "Ít nhất 6 ký tự.",
      "submit": "Cập nhật mật khẩu",
      "success": "Đổi mật khẩu thành công.",
      "errorCurrentRequired": "Vui lòng nhập mật khẩu hiện tại.",
      "errorNewMin": "Mật khẩu mới phải có ít nhất 6 ký tự.",
      "errorConfirmMismatch": "Xác nhận mật khẩu không khớp."
    },
    "home": "Trang chủ",
    "back": "Quay lại",
    "licenseInfo": "Thông tin bản quyền",
    "system": "Hệ thống",
    "skipToMain": "Chuyển đến nội dung chính",
    "collapseSidebar": "Thu gọn sidebar",
    "expandSidebar": "Mở rộng sidebar",
    "closeOverlay": "Đóng overlay",
    "notification": "Thông báo",
    "userMenu": "Menu người dùng",
    "guestUser": "Guest User",
    "roleAdmin": "Admin",
    "roleMember": "Member",
    "profile": "Hồ sơ cá nhân",
    "logout": "Đăng xuất",
    "logoutConfirmTitle": "Xác nhận đăng xuất",
    "logoutConfirmMessage": "Bạn có chắc chắn muốn kết thúc phiên làm việc?",
    "logoutCancel": "Hủy bỏ",
    "defaultAppDescription": "Enterprise Platform",
    "mainNav": "Điều hướng chính",
    "changePasswordLabel": "Đổi mật khẩu",
    "commandPalette": {
      "title": "Điều hướng nhanh",
      "placeholder": "Tìm trang hoặc đường dẫn…",
      "empty": "Không có kết quả",
      "hint": "Esc đóng · Enter mở · ↑↓ chọn",
      "groupGeneral": "Chung",
      "groupSystem": "Hệ thống",
      "groupAccount": "Tài khoản"
    }
  },
  "shared": {
    "export": {
      "title": "Xuất dữ liệu",
      "format": "Định dạng",
      "scope": "Phạm vi",
      "scopeAll": "Tất cả",
      "scopeCurrentPage": "Trang hiện tại",
      "scopeSelected": "Đã chọn",
      "rows": "dòng",
      "selectColumns": "Chọn cột xuất",
      "deselectAll": "Bỏ chọn hết",
      "selectAll": "Chọn tất cả",
      "pdfHeader": "Xuất ngày: {{date}} | {{count}} bản ghi",
      "exporting": "Đang xuất...",
      "exportRows": "Xuất {{count}} dòng"
    },
    "import": {
      "title": "Import dữ liệu",
      "subtitle": "Tải lên file Excel hoặc CSV",
      "dropHere": "Kéo thả file vào đây",
      "orClickToSelect": "hoặc nhấn để chọn file (.xlsx, .xls, .csv)",
      "downloadTemplate": "Tải file mẫu (.xlsx)",
      "rowsRead": "Đã đọc {{count}} dòng dữ liệu",
      "systemColumn": "Cột hệ thống",
      "fileColumn": "Cột trong file",
      "skipColumn": "-- Bỏ qua --",
      "preview": "Xem trước (5 dòng đầu)",
      "success": "Import thành công!",
      "successCount": "{{count}} bản ghi đã được nhập",
      "error": "Không import được",
      "noDataOrHeader": "File không có dữ liệu hoặc thiếu header",
      "cannotReadFile": "Không thể đọc file. Vui lòng kiểm tra định dạng.",
      "missingRequiredColumns": "Chưa mapping cột bắt buộc: {{columns}}",
      "rowEmptyField": "Dòng {{row}}: \"{{column}}\" không được để trống",
      "importError": "Lỗi khi import dữ liệu",
      "importRows": "Import {{count}} dòng"
    },
    "empty": {
      "title": "Không có dữ liệu",
      "description": "Chưa có dữ liệu. Thử thêm bản ghi hoặc điều chỉnh bộ lọc."
    },
    "error": {
      "title": "Đã xảy ra lỗi",
      "message": "Không thể tải dữ liệu. Vui lòng thử lại.",
      "retry": "Tải lại",
      "backHome": "Về trang chủ",
      "reloading": "Đang tải lại...",
      "network": "Lỗi kết nối mạng. Kiểm tra internet và thử lại.",
      "unauthorized": "Phiên đăng nhập hết hạn hoặc không có quyền truy cập.",
      "forbidden": "Bạn không có quyền thực hiện thao tác này.",
      "notFound": "Không tìm thấy tài nguyên.",
      "server": "Lỗi máy chủ. Vui lòng thử lại sau.",
      "timeout": "Hết thời gian chờ. Vui lòng thử lại.",
      "unknown": "Đã xảy ra lỗi không xác định. Vui lòng thử lại.",
      "beforeInitialization": "Lỗi khởi tạo: không thể truy cập trước khi khởi tạo. Vui lòng tải lại trang.",
      "notDefined": "Tham chiếu lỗi: thành phần chưa được định nghĩa. Vui lòng tải lại trang.",
      "notFunction": "Lỗi gọi hàm: giá trị không phải là hàm. Vui lòng tải lại trang.",
      "chunkLoad": "Không tải được phần mềm. Vui lòng tải lại trang.",
      "devDetail": "Chi tiết kỹ thuật (chế độ phát triển):"
    },
    "mobileFilter": {
      "title": "Bộ lọc",
      "searchPlaceholder": "Tìm {{label}}...",
      "selectAll": "Chọn tất cả",
      "notFound": "Không tìm thấy",
      "clear": "Xóa bộ lọc"
    },
    "mobileActions": {
      "title": "Thao tác"
    }
  },
  "page": {
    "home": {
      "greeting": "Xin chào,",
      "greetingMorning": "Chào buổi sáng",
      "greetingAfternoon": "Chào buổi chiều",
      "greetingEvening": "Chào buổi tối",
      "adminFallback": "Quản trị viên",
      "systemModuleDesc": "Cấu hình, phân quyền và nhân sự.",
      "licenseInfoDesc": "Quản lý sở hữu trí tuệ và thông tin nhà phát triển."
    },
    "license": {
      "title": "Thông tin Bản quyền",
      "subtitle": "Quản lý sở hữu trí tuệ và thông tin nhà phát triển",
      "unitTitle": "Đơn vị xây dựng & Phát triển",
      "companyName": "Tên công ty / Tổ chức",
      "representative": "Người đại diện",
      "taxCode": "Mã số thuế",
      "address": "Địa chỉ trụ sở",
      "rightsTitle": "Quyền hạn & Bảo mật",
      "rightsIntro": "Phần mềm này cùng toàn bộ mã nguồn, giao diện và cơ sở dữ liệu thuộc quyền sở hữu trí tuệ duy nhất của Công ty ABC. Mọi hành vi sao chép, chỉnh sửa hoặc phân phối lại mà không có sự đồng ý bằng văn bản đều là vi phạm pháp luật.",
      "version": "Phiên bản hiện tại",
      "licenseDate": "Ngày cấp phép",
      "status": "Trạng thái",
      "statusRegistered": "Đã đăng ký bản quyền tại Cục Sở hữu trí tuệ.",
      "communityLinks": "Liên kết cộng đồng",
      "website": "Website chính thức",
      "fanpage": "Fanpage Facebook",
      "communityGroup": "Group Cộng đồng",
      "zaloGroup": "Cộng đồng Zalo",
      "tiktok": "Kênh TikTok",
      "supportTitle": "Hỗ trợ kỹ thuật?",
      "supportDesc": "Gặp sự cố hoặc cần tư vấn thêm về giải pháp?",
      "contactHotline": "Liên hệ Hotline",
      "footer": "© 2024 - 2026 Bản quyền thuộc về Công ty ABC. Được bảo vệ bởi hệ thống bảo vệ bản quyền số quốc tế.",
      "technicalContact": "Liên hệ Kỹ thuật",
      "businessContact": "Liên hệ Kinh doanh",
      "contactName": "Tên",
      "contactPosition": "Chức vụ",
      "contactPhone": "Số điện thoại",
      "contactEmail": "Email"
    },
    "placeholder": {
      "backToHome": "Quay lại trang chủ",
      "backToSubmenu": "Quay lại",
      "moduleComingSoon": "Chức năng đang được phát triển.",
      "title": "Module đang được phát triển",
      "description": "Chúng tôi đang nỗ lực hoàn thiện tính năng này để mang lại trải nghiệm tốt nhất cho bạn. Vui lòng quay lại sau!",
      "descriptionWithModule": "Tính năng {{name}} đang được hoàn thiện. Vui lòng quay lại sau!",
      "badgeComingSoon": "Sắp ra mắt",
      "refreshPage": "Làm mới trang",
      "expectedCompletion": "Dự kiến hoàn thành: Quý 2 - 2026",
      "exampleDoc": "Công văn",
      "exampleContract": "Hợp đồng",
      "exampleRecruit": "Tuyển dụng",
      "exampleAttendance": "Chấm công",
      "exampleCampaign": "Chiến dịch",
      "exampleAccounting": "Kế toán",
      "exampleOrder": "Đặt hàng",
      "exampleInventory": "Tồn kho"
    },
    "login": {
      "emailRequired": "Vui lòng nhập email",
      "emailInvalid": "Email không hợp lệ",
      "usernameRequired": "Vui lòng nhập tên tài khoản",
      "usernameMin": "Tên tài khoản phải có ít nhất 2 ký tự",
      "username": "Tên tài khoản",
      "usernamePlaceholder": "VD: admin",
      "passwordMin": "Mật khẩu phải có ít nhất 6 ký tự",
      "mockUserName": "Lê Minh Công",
      "loginSuccess": "Đăng nhập thành công!",
      "googleUser": "Google User",
      "googleSuccess": "Đăng nhập bằng Google thành công!",
      "heading": "Quản lý doanh nghiệp",
      "headingHighlight": "thông minh & hiệu quả",
      "description": "Nền tảng tích hợp AI giúp tối ưu hóa quy trình nhân sự, tài chính và vận hành hệ thống của bạn trong một giao diện duy nhất.",
      "feature1": "Tích hợp AI Assistant mạnh mẽ",
      "feature2": "Dashboard phân tích dữ liệu Realtime",
      "feature3": "Bảo mật dữ liệu tiêu chuẩn Enterprise",
      "welcome": "Chào mừng trở lại",
      "welcomeDesc": "Nhập tên tài khoản và mật khẩu để truy cập.",
      "email": "Email",
      "emailPlaceholder": "name@company.com",
      "password": "Mật khẩu",
      "showPassword": "Hiện mật khẩu",
      "hidePassword": "Ẩn mật khẩu",
      "forgotPassword": "Quên mật khẩu?",
      "rememberMe": "Ghi nhớ đăng nhập",
      "loginButton": "Đăng nhập",
      "orLoginWith": "Hoặc đăng nhập bằng",
      "forgotAccountLabel": "Tên tài khoản",
      "forgotAccountPlaceholder": "Nhập tên tài khoản đã đăng ký",
      "noAccount": "Bạn chưa có tài khoản?",
      "register": "Đăng ký ngay",
      "copyright": "© 2024",
      "companyFallback": "5F Quản lý thiết bị",
      "legal": "Bảo mật • Điều khoản sử dụng",
      "forgotPasswordTitle": "Quên mật khẩu",
      "forgotPasswordDesc": "Nhập tên tài khoản đã đăng ký, chúng tôi sẽ gửi hướng dẫn khôi phục mật khẩu.",
      "sendRecovery": "Gửi link khôi phục",
      "recoverySent": "Đã gửi thông tin khôi phục về email của bạn. Vui lòng kiểm tra hộp thư.",
      "recoverySentTitle": "Đã gửi"
    },
    "register": {
      "title": "Tạo tài khoản",
      "desc": "Chỉ cần nhập tên đăng nhập (không cần @gmail.com — hệ thống tự thêm khi xác thực Supabase).",
      "fullName": "Họ và tên",
      "fullNamePlaceholder": "Nguyễn Văn A",
      "password": "Mật khẩu",
      "passwordPlaceholder": "Ít nhất 6 ký tự",
      "confirmPassword": "Xác nhận mật khẩu",
      "confirmPasswordPlaceholder": "Nhập lại mật khẩu",
      "submit": "Đăng ký",
      "success": "Đăng ký thành công! Bạn có thể đăng nhập ngay.",
      "passwordMismatch": "Mật khẩu xác nhận không khớp",
      "fullNameMin": "Họ tên phải có ít nhất 2 ký tự",
      "hasAccount": "Đã có tài khoản?",
      "loginLink": "Đăng nhập"
    },
    "profile": {
      "nameMin": "Tên phải có ít nhất 2 ký tự",
      "emailInvalid": "Địa chỉ email không hợp lệ",
      "bioMax": "Giới thiệu không được quá 160 ký tự",
      "defaultBio": "Lập trình viên Frontend | Đam mê công nghệ",
      "updateSuccess": "Cập nhật hồ sơ thành công!",
      "userNotFound": "Không tìm thấy thông tin người dùng.",
      "title": "Hồ sơ cá nhân",
      "description": "Quản lý thông tin tài khoản và cài đặt của bạn.",
      "activeStatus": "Đang hoạt động",
      "roleUser": "User",
      "joinedAt": "Tham gia",
      "verified": "Tài khoản xác thực",
      "avatarAlt": "Avatar của {{name}}",
      "avatarAltFallback": "Avatar người dùng",
      "basicInfo": "Thông tin cơ bản",
      "fullName": "Họ và tên",
      "namePlaceholder": "Nhập tên của bạn",
      "email": "Email",
      "emailPlaceholder": "email@example.com",
      "bio": "Giới thiệu",
      "bioPlaceholder": "Mô tả ngắn về bản thân...",
      "bioHint": "Tối đa 160 ký tự",
      "settingsSection": "Cài đặt",
      "emailNotification": "Thông báo qua Email",
      "emailNotificationDesc": "Nhận cập nhật về hoạt động tài khoản và tin tức mới nhất.",
      "viewOnlyBanner": "Bạn chỉ có quyền xem hồ sơ.",
      "changeAvatar": "Đổi ảnh đại diện",
      "changePassword": "Đổi mật khẩu",
      "changePasswordTitle": "Đổi mật khẩu",
      "changePasswordDesc": "Nhập mật khẩu hiện tại và mật khẩu mới.",
      "currentPassword": "Mật khẩu hiện tại",
      "newPassword": "Mật khẩu mới",
      "confirmPassword": "Xác nhận mật khẩu mới",
      "passwordPlaceholder": "••••••••",
      "avatarModalTitle": "Đổi ảnh đại diện",
      "avatarModalHint": "Kéo thả hoặc chọn ảnh. PNG, JPG, tối đa 2MB.",
      "emptyField": "Chưa cập nhật",
      "detailSectionsTitle": "Thông tin chi tiết",
      "comingSoon": "Sắp ra mắt",
      "comingSoonDesc": "Tính năng đang được phát triển.",
      "avatarUpdateSuccess": "Đã cập nhật ảnh đại diện."
    },
    "systemDashboard": {
      "orgChartGroup": "Sơ đồ",
      "employee": "Nhân viên",
      "employeeDesc": "Hồ sơ và thông tin nhân sự.",
      "department": "Phòng ban",
      "departmentDesc": "Cơ cấu tổ chức đơn vị.",
      "position": "Chức vụ",
      "positionDesc": "Quản lý các vị trí công việc.",
      "securityGroup": "Bảo mật & Cấu hình",
      "companyInfo": "Thông tin công ty",
      "companyInfoDesc": "Thiết lập thông tin pháp nhân.",
      "permission": "Phân quyền",
      "permissionDesc": "Vai trò và quyền hạn."
    }
  },
  "notification": {
    "title": "Thông báo",
    "markAllRead": "Đánh dấu tất cả đã đọc",
    "clearAll": "Xóa tất cả",
    "empty": "Chưa có thông báo",
    "emptyHint": "Các thông báo mới sẽ hiển thị tại đây.",
    "remove": "Xóa thông báo",
    "viewAll": "Xem tất cả thông báo",
    "collapse": "Thu gọn"
  },
  "breadcrumb": {
    "label": "Đường dẫn",
    "home": "Trang chủ",
    "licenseInfo": "Thông tin bản quyền",
    "goHome": "Về trang chủ",
    "systemAdmin": "Hệ thống",
    "employee": "Nhân sự",
    "department": "Phòng ban",
    "position": "Chức vụ",
    "companyInfo": "Thông tin công ty",
    "permission": "Phân quyền",
    "profile": "Hồ sơ cá nhân"
  },
  "clock": {
    "sunday": "Chủ nhật",
    "monday": "Thứ 2",
    "tuesday": "Thứ 3",
    "wednesday": "Thứ 4",
    "thursday": "Thứ 5",
    "friday": "Thứ 6",
    "saturday": "Thứ 7"
  },
  "common": {
    "save": "Lưu",
    "required": "Trường bắt buộc",
    "saving": "Đang lưu...",
    "cancel": "Hủy",
    "close": "Đóng",
    "create": "Thêm",
    "view": "Xem",
    "edit": "Sửa",
    "delete": "Xóa",
    "add": "Thêm",
    "confirm": "Xác nhận",
    "deleteAll": "Xóa tất cả",
    "deleteManyConfirm": "Xóa {{count}} bản ghi đã chọn?",
    "statusChangeManyConfirm": "Đổi trạng thái {{count}} bản ghi sang {{status}}?",
    "back": "Quay lại",
    "search": "Tìm kiếm...",
    "searchPlaceholder": "Tìm kiếm . . .",
    "searchShortcut": "Tìm kiếm... (nhấn /)",
    "unknown": "Không xác định",
    "noData": "Không có dữ liệu",
    "noResults": "Không có kết quả phù hợp.",
    "loading": "Đang tải...",
    "active": "Hoạt động",
    "inactive": "Ngừng hoạt động",
    "status": "Trạng thái",
    "actions": "Thao tác",
    "moreRowActions": "Thao tác thêm",
    "description": "Mô tả",
    "all": "Tất cả",
    "perPage": "/ trang",
    "apply": "Áp dụng",
    "reset": "Khôi phục mặc định",
    "import": "Nhập",
    "export": "Xuất",
    "addNew": "Thêm",
    "activate": "Kích hoạt",
    "deactivate": "Tắt",
    "selected": "đã chọn",
    "selectAll": "Chọn tất cả",
    "select": "Chọn",
    "deselectAll": "Bỏ chọn tất cả",
    "clearSelection": "Xóa chọn",
    "clearFilter": "Xóa bộ lọc",
    "clearFilters": "Xóa {{count}} bộ lọc",
    "columnDisplay": "Cột hiển thị",
    "columnOptions": "Tùy chọn cột",
    "saveChanges": "Lưu",
    "cancelAction": "Hủy",
    "loadingData": "Đang tải dữ liệu",
    "processing": "Đang xử lý...",
    "finish": "Hoàn tất",
    "selectFile": "Chọn file khác",
    "allStatuses": "Tất cả trạng thái",
    "activeStatus": "Đang hoạt động",
    "inactiveStatus": "Ngừng hoạt động",
    "noDescription": "Không có mô tả",
    "error": "Đã xảy ra lỗi",
    "errorLoadData": "Không thể tải dữ liệu. Vui lòng thử lại.",
    "retry": "Thử lại",
    "firstPage": "Trang đầu",
    "prevPage": "Trang trước",
    "nextPage": "Trang sau",
    "lastPage": "Trang cuối",
    "doubleClickToPage": "Nhấn đúp để nhập trang"
  },
  "stats": {
    "columnLabel": "Tiêu đề",
    "columnValue": "Giá trị",
    "noData": "Không có dữ liệu",
    "trendVsLastPeriod": "So với kỳ trước"
  },
  "guide": {
    "buttonTitle": "Hướng dẫn"
  },
  "settings": {
    "primaryColor": "Màu",
    "colorBlue": "Xanh dương",
    "colorViolet": "Tím",
    "colorEmerald": "Xanh lá",
    "colorRose": "Hồng",
    "colorAmber": "Cam vàng",
    "colorOrange": "Cam",
    "colorCyan": "Xanh lơ",
    "colorSlate": "Xám"
  }
} as const;
